---
- hosts: servers
  become: yes #become sudo
  tasks:
    - name: Ensure NTP is installed
      apt: name=ntp state=present
    - name: Ensure NTP is running
      service: name=ntpd state=started enable=yes